/**
 * In-memory Mock PostgreSQL Database State
 * Pre-seeded with departments, cost centers, custom field definitions, and employees.
 */

import { CostCenter, CustomFieldDefinition, Department, Employee, PayrollRun } from '../types/hr';

export const INITIAL_DEPARTMENTS: Department[] = [
  {
    id: 'dept-001',
    tenantId: 'tenant-acme-corp',
    code: 'ENG',
    name: 'Engineering & Technology',
    sapCostCenterRef: '10101101',
  },
  {
    id: 'dept-002',
    tenantId: 'tenant-acme-corp',
    code: 'SALES',
    name: 'Global Sales & Marketing',
    sapCostCenterRef: '10101201',
  },
  {
    id: 'dept-003',
    tenantId: 'tenant-acme-corp',
    code: 'OPS',
    name: 'Operations & Logistics',
    sapCostCenterRef: '10101301',
  },
  {
    id: 'dept-004',
    tenantId: 'tenant-acme-corp',
    code: 'FIN',
    name: 'Finance & Controlling',
    sapCostCenterRef: '10101401',
  },
];

export const INITIAL_COST_CENTERS: CostCenter[] = [
  {
    id: 'cc-001',
    tenantId: 'tenant-acme-corp',
    costCenterCode: 'CC_ENG_CORE',
    sapCostCenter: '10101101', // SAP KOSTL
    sapCompanyCode: '1010',     // SAP BUKRS
    name: 'Software Engineering Core',
    responsiblePerson: 'Dr. Marcus Vance',
    isActive: true,
  },
  {
    id: 'cc-002',
    tenantId: 'tenant-acme-corp',
    costCenterCode: 'CC_SALES_EMEA',
    sapCostCenter: '10101201',
    sapCompanyCode: '1010',
    name: 'Sales EMEA Operations',
    responsiblePerson: 'Elena Rostova',
    isActive: true,
  },
  {
    id: 'cc-003',
    tenantId: 'tenant-acme-corp',
    costCenterCode: 'CC_OPS_LOG',
    sapCostCenter: '10101301',
    sapCompanyCode: '1010',
    name: 'Supply Chain & Logistics',
    responsiblePerson: 'Tariq Al-Mansoor',
    isActive: true,
  },
  {
    id: 'cc-004',
    tenantId: 'tenant-acme-corp',
    costCenterCode: 'CC_FIN_CTRL',
    sapCostCenter: '10101401',
    sapCompanyCode: '1010',
    name: 'Corporate Controlling',
    responsiblePerson: 'Sophia Chen',
    isActive: true,
  },
];

export const INITIAL_CUSTOM_FIELD_DEFINITIONS: CustomFieldDefinition[] = [
  {
    id: 'cf-001',
    tenantId: 'tenant-acme-corp',
    fieldKey: 'housing_allowance',
    fieldLabel: 'Monthly Housing Allowance',
    fieldType: 'currency',
    isRequired: false,
    defaultValue: 1500,
    sapInfotype: 'IT0014', // Recurring Payments/Deductions in SAP
    description: 'Tenant specific recurring housing subsidy mapped to wage type WT1020',
  },
  {
    id: 'cf-002',
    tenantId: 'tenant-acme-corp',
    fieldKey: 'transport_allowance',
    fieldLabel: 'Transportation Allowance',
    fieldType: 'currency',
    isRequired: false,
    defaultValue: 400,
    sapInfotype: 'IT0014',
    description: 'Fixed commuter allowance mapped to SAP wage type WT1030',
  },
  {
    id: 'cf-003',
    tenantId: 'tenant-acme-corp',
    fieldKey: 'medical_clearance_verified',
    fieldLabel: 'Occupational Medical Clearance',
    fieldType: 'boolean',
    isRequired: true,
    defaultValue: true,
    sapInfotype: 'IT0028', // Internal Medical Services
    description: 'Required clearance for insurance underwriting compliance',
  },
  {
    id: 'cf-004',
    tenantId: 'tenant-acme-corp',
    fieldKey: 'remote_work_tier',
    fieldLabel: 'Workplace Arrangement Tier',
    fieldType: 'select',
    isRequired: false,
    defaultValue: 'Hybrid 3/2',
    options: ['On-Site 100%', 'Hybrid 3/2', 'Hybrid 2/3', 'Full Remote'],
    sapInfotype: 'IT0001', // Org Assignment
    description: 'Affects tax residency and local commuter taxation',
  },
  {
    id: 'cf-005',
    tenantId: 'tenant-acme-corp',
    fieldKey: 'sap_personnel_subarea',
    fieldLabel: 'SAP Personnel Subarea (BTRTL)',
    fieldType: 'text',
    isRequired: false,
    defaultValue: '0001',
    sapInfotype: 'IT0001',
    description: 'Four-digit SAP Personnel Subarea code for tax calculation',
  },
];

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-001',
    tenantId: 'tenant-acme-corp',
    firstName: 'Amira',
    lastName: 'Khoury',
    email: 'amira.khoury@acme-corp.com',
    role: 'Principal Cloud Architect',
    departmentId: 'dept-001',
    costCenterId: 'cc-001',
    basicSalary: 9500.00,
    currency: 'USD',
    employmentStatus: 'ACTIVE',
    hireDate: '2023-03-15',
    sapEmployeeId: '00049281',
    sapCostCenter: '10101101',
    sapCompanyCode: '1010',
    sapPersonnelArea: '1000',
    sapSyncStatus: 'SYNCED',
    sapLastSyncedAt: '2026-09-15T08:30:00Z',
    customAttributes: {
      housing_allowance: 2200,
      transport_allowance: 500,
      medical_clearance_verified: true,
      remote_work_tier: 'Hybrid 3/2',
      sap_personnel_subarea: '0001',
    },
    createdAt: '2023-03-15T09:00:00Z',
    updatedAt: '2026-09-15T08:30:00Z',
  },
  {
    id: 'emp-002',
    tenantId: 'tenant-acme-corp',
    firstName: 'Mateo',
    lastName: 'Silva',
    email: 'mateo.silva@acme-corp.com',
    role: 'Senior Enterprise Account Executive',
    departmentId: 'dept-002',
    costCenterId: 'cc-002',
    basicSalary: 8200.00,
    currency: 'USD',
    employmentStatus: 'ACTIVE',
    hireDate: '2023-08-01',
    sapEmployeeId: '00049282',
    sapCostCenter: '10101201',
    sapCompanyCode: '1010',
    sapPersonnelArea: '1000',
    sapSyncStatus: 'SYNCED',
    sapLastSyncedAt: '2026-09-15T08:30:00Z',
    customAttributes: {
      housing_allowance: 1800,
      transport_allowance: 650,
      medical_clearance_verified: true,
      remote_work_tier: 'Hybrid 2/3',
      sap_personnel_subarea: '0002',
    },
    createdAt: '2023-08-01T10:00:00Z',
    updatedAt: '2026-09-15T08:30:00Z',
  },
  {
    id: 'emp-003',
    tenantId: 'tenant-acme-corp',
    firstName: 'Hassan',
    lastName: 'Nasser',
    email: 'hassan.nasser@acme-corp.com',
    role: 'Logistics Operations Lead',
    departmentId: 'dept-003',
    costCenterId: 'cc-003',
    basicSalary: 7100.00,
    currency: 'USD',
    employmentStatus: 'ACTIVE',
    hireDate: '2024-01-10',
    sapEmployeeId: '00049283',
    sapCostCenter: '10101301',
    sapCompanyCode: '1010',
    sapPersonnelArea: '1000',
    sapSyncStatus: 'SYNCED',
    sapLastSyncedAt: '2026-09-15T08:30:00Z',
    customAttributes: {
      housing_allowance: 1500,
      transport_allowance: 400,
      medical_clearance_verified: true,
      remote_work_tier: 'On-Site 100%',
      sap_personnel_subarea: '0001',
    },
    createdAt: '2024-01-10T09:00:00Z',
    updatedAt: '2026-09-15T08:30:00Z',
  },
];

export const INITIAL_PAYROLL_RUNS: PayrollRun[] = [];
